GET http://localhost:3000/admins HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sIjoib3duZXIiLCJpYXQiOjE2ODI0MzU0NDYsImV4cCI6MTY4MjQ0MjY0Nn0.BUw-TLDw65VUAQBLZzqgmfEvMU1ubpijavTpLUwZ484

###

GET http://localhost:3000/admins/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sIjoib3duZXIiLCJpYXQiOjE2ODI0MzU0NDYsImV4cCI6MTY4MjQ0MjY0Nn0.BUw-TLDw65VUAQBLZzqgmfEvMU1ubpijavTpLUwZ484

###

POST http://localhost:3000/admins/register HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ2YmFkNDJmY2JkMDNmNzEyYzU3YjkiLCJyb2wiOiJvd25lciIsImlhdCI6MTY4MjM2NTQ2NCwiZXhwIjoxNjgyMzcyNjY0fQ.DIAt5vT22hyD7LY-b_gMHRnR7H-XYP_wund5EW0ZbG8
Content-Type: application/json

{
    "username": "owner",
    "name": "Héctor Paredes Benavides",
    "email": "hector.paredes@live.u-tad.com",
    "password": "Abc123..",
    "description": "Esta es mi nueva descripción",
    "avatar": "NONE",
    "country": "España",
    "city": "Madrid",
    "preferences": ["hotel", "restaurant"],
    "allowAdvertising": false
}

###

PUT http://localhost:3000/admins/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sIjoib3duZXIiLCJpYXQiOjE2ODI4NjU2NjgsImV4cCI6MTY4Mjg3Mjg2OH0.eDzrXukn73qdCPsBQlZmNNciMGpti1wm08Qxr6i3cmQ
Content-Type: application/json

{
    "username": "owner",
    "name": "Héctor Paredes Benavides",
    "email": "hector.paredes@live.u-tad.com",
    "password": "Abc123..",
    "description": "Esta es mi nueva descripción",
    "avatar": "NONE",
    "country": "España",
    "city": "Madrid",
    "preferences": ["hotel", "restaurant"],
    "allowAdvertising": false
}

###

DELETE http://localhost:3000/admins/6446dd552fa9fe672fa44492 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ2YmFkNDJmY2JkMDNmNzEyYzU3YjkiLCJyb2wiOiJvd25lciIsImlhdCI6MTY4MjM2NTQ2NCwiZXhwIjoxNjgyMzcyNjY0fQ.DIAt5vT22hyD7LY-b_gMHRnR7H-XYP_wund5EW0ZbG8

###

PUT http://localhost:3000/admins/promote/6446d69c231fe9a3eaca547f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDQ2YmFkNDJmY2JkMDNmNzEyYzU3YjkiLCJyb2wiOiJvd25lciIsImlhdCI6MTY4MjM2NDU4NywiZXhwIjoxNjgyMzcxNzg3fQ.9mnpdOf_bcifoEtHhRFe6I4q-Qulzkaz0Czm0FWB_5U

###