GET http://localhost:3000/merchants HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgyNjI1MzkyLCJleHAiOjE2ODI2MzI1OTJ9.k4d7dPSKVAl9LwnUV4b27xgqKZwCcHwfBKsb2YDyjD8

###

GET http://localhost:3000/merchants/3 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiaWF0IjoxNjgyNjI1MzkyLCJleHAiOjE2ODI2MzI1OTJ9.k4d7dPSKVAl9LwnUV4b27xgqKZwCcHwfBKsb2YDyjD8

###

POST http://localhost:3000/merchants/register HTTP/1.1
Content-Type: application/json

{
    "merchantname": "tienda",
    "name": "La tienda ...",
    "email": "hectorpbenavides@gmail.com",
    "password": "Abc123..",
    "cif": "123456789A",
    "phone": "123456789",
    "country": "España",
    "city": "Madrid",
    "address": "C/ Gran Vía, 8"
}

###

POST http://localhost:3000/merchants/login HTTP/1.1
Content-Type: application/json

{
    "merchantname": "hectorpbenavides@gmail.com",
    "password": "Abc123.."
}

###

POST http://localhost:3000/merchants/restorepassword/email HTTP/1.1
Content-Type: application/json

{
    "email": "hectorpbenavides@gmail.com"
}

###

POST http://localhost:3000/merchants/restorepassword/code HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29kZSI6Ijc4MjU0NiIsInBhc3N3b3JkIjoiJDJhJDEwJHowZ0tGL3FZZ2xmeEJkemRqLnczQWUvRy5UUjRORDB5dEQwSlc1cEVCbzBsbzVLNmI0U1RpIiwicGFzc3dvcmRSZXN0b3JhdGlvbklEIjo0LCJtYXhBdHRlbXB0cyI6NSwiaWF0IjoxNjgyNjI4MTk0LCJleHAiOjE2ODI2Mjk5OTR9.-Rw_qBFMHGZV9U5ir01LyYBizcg62VzjcIjrAoOCp0k
Content-Type: application/json

{
    "code": "782546"
}

###

PUT http://localhost:3000/merchants/restorepassword HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGFzc3dvcmQiOiIkMmEkMTAkejBnS0YvcVlnbGZ4QmR6ZGoudzNBZS9HLlRSNE5EMHl0RDBKVzVwRUJvMGxvNUs2YjRTVGkiLCJwYXNzd29yZFJlc3RvcmF0aW9uSUQiOjQsImlhdCI6MTY4MjYyODIyMSwiZXhwIjoxNjgyNjI4NTIxfQ.wiWG8ZlfBum9p3xSM4JJTjMA9aeb_nW_YsC4I3Ydtzk
Content-Type: application/json

{
    "password": "Abc123..."
}

###

PUT http://localhost:3000/merchants/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgyNjI4Mjc1LCJleHAiOjE2ODI2MzU0NzV9.x2Ax5WE-IvNEVbDP3jGQy1Ji_wH62Z7GIaM9YUMqbQg
Content-Type: application/json

{
    "merchantname": "tienda",
    "name": "La tienda ... 2",
    "email": "hectorpbenavides@gmail.com",
    "password": "Abc123..",
    "cif": "123456789A",
    "phone": "123456789",
    "country": "España",
    "city": "Madrid",
    "address": "C/ Gran Vía, 8"
}

###

DELETE http://localhost:3000/merchants/1 HTTP/1.1

###

PUT http://localhost:3000/merchants/activate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sIjoib3duZXIiLCJpYXQiOjE2ODI4NjU3MDAsImV4cCI6MTY4Mjg3MjkwMH0.XDArfGlFmB2_Ubr8BuYFmCY8eWZ32dbUfRCn9NDLUIU HTTP/1.1

###

PUT http://localhost:3000/merchants/accept/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sIjoib3duZXIiLCJpYXQiOjE2ODI4NjU3MDAsImV4cCI6MTY4Mjg3MjkwMH0.XDArfGlFmB2_Ubr8BuYFmCY8eWZ32dbUfRCn9NDLUIU

###