GET http://localhost:3000/merchants HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sIjoib3duZXIiLCJpYXQiOjE2ODMzMzIyNTIsImV4cCI6MTY4MzMzOTQ1Mn0.Uyv_7pLqT5lc6QAclYaKtW3hwiMd5RG9BKC2BqYo8Vw

###

GET http://localhost:3000/merchants/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sIjoib3duZXIiLCJpYXQiOjE2ODMzMzM0OTgsImV4cCI6MTY4MzM0MDY5OH0.rSGzT45eTk7MzSNjJBt3G8CGXv1VxzFNMoa6gUI5t38

###

POST http://localhost:3000/merchants/register HTTP/1.1
Content-Type: application/json

{
    "merchantname": "tienda",
    "name": "La tienda ...",
    "email": "hectorpbenavides@gmail.com",
    "password": "Abc123..",
    "cif": "123456789A",
    "phone": "123456789",
    "country": "España",
    "city": "Madrid",
    "address": "C/ Gran Vía, 8"
}

###

POST http://localhost:3000/merchants/login HTTP/1.1
Content-Type: application/json

{
    "merchantname": "hectorpbenavides@gmail.com",
    "password": "Abc123.."
}

###

POST http://localhost:3000/merchants/restorepassword/email HTTP/1.1
Content-Type: application/json

{
    "email": "hectorpbenavides@gmail.com"
}

###

POST http://localhost:3000/merchants/restorepassword/code HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiY29kZSI6IjQzODYwMSIsInBhc3N3b3JkIjoiJDJhJDEwJEhzREl0bWVYNTdzekUyS3o0ZDdUcmUyTUNieE9ycm9DSEpneTZvcmFXcC5QLmE1b0pDRmFXIiwicGFzc3dvcmRSZXN0b3JhdGlvbklEIjoxLCJtYXhBdHRlbXB0cyI6NSwiaWF0IjoxNjgzMzI5NzU2LCJleHAiOjE2ODMzMzE1NTZ9.0IGEkJUCHeLB3bSBlrDcZOM6VawFk5pShCKcpy0Pii8
Content-Type: application/json

{
    "code": "438601"
}

###

PUT http://localhost:3000/merchants/restorepassword HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicGFzc3dvcmQiOiIkMmEkMTAkSHNESXRtZVg1N3N6RTJLejRkN1RyZTJNQ2J4T3Jyb0NISmd5Nm9yYVdwLlAuYTVvSkNGYVciLCJwYXNzd29yZFJlc3RvcmF0aW9uSUQiOjEsImlhdCI6MTY4MzMyOTc4NCwiZXhwIjoxNjgzMzMwMDg0fQ.02mgDHYngVbidutFgw9KvmBkPr1Q82m_hUOBy3Iga3g
Content-Type: application/json

{
    "password": "Abc123..."
}

###

PUT http://localhost:3000/merchants/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgyNjI4Mjc1LCJleHAiOjE2ODI2MzU0NzV9.x2Ax5WE-IvNEVbDP3jGQy1Ji_wH62Z7GIaM9YUMqbQg
Content-Type: application/json

{
    "merchantname": "tienda",
    "name": "La tienda ... 2",
    "email": "hectorpbenavides@gmail.com",
    "password": "Abc123..",
    "cif": "123456789A",
    "phone": "123456789",
    "country": "España",
    "city": "Madrid",
    "address": "C/ Gran Vía, 8"
}

###

DELETE http://localhost:3000/merchants/1 HTTP/1.1

###

PUT http://localhost:3000/merchants/activate/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzMzI5Njc1LCJleHAiOjE2ODMzMzY4NzV9.HVv9u68DL-xUzJ2g1gR4DVRt91Ug9ZofBETxXXcoycI HTTP/1.1

###

PUT http://localhost:3000/merchants/accept/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sIjoib3duZXIiLCJpYXQiOjE2ODMzMjk3MTgsImV4cCI6MTY4MzMzNjkxOH0.Bpel1eKL7QdEzgok5oO7KKgl6ozMIf_CapcbxF2tD54

###