POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "hecpabe",
    "name": "Héctor Paredes Benavides",
    "email": "hectorpbenavides@gmail.com",
    "password": "Abc123..",
    "description": "Esta es mi nueva descripción",
    "avatar": 1,
    "country": "España",
    "city": "Madrid",
    "preferences": ["hotel", "restaurant"],
    "allowAdvertising": false
}

###

GET http://localhost:3000/users HTTP/1.1

###

GET http://localhost:3000/users/1 HTTP/1.1

###

GET http://localhost:3000/users/preferences/Ropa HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjgzMjg1NDQyLCJleHAiOjE2ODMyOTI2NDJ9.Q6p7rdMZFRC0EnUbee-WjX4bSCr5jHy5qG5zRH3bu1w

###

PUT http://localhost:3000/users/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Miwicm9sIjoidXNlciIsImlhdCI6MTY4Mjg3OTk3MSwiZXhwIjoxNjgyODg3MTcxfQ.pMPo5MvbuHqIwYU5Q89NHfmf8ErbmeXjRgHYUPIoXQE
Content-Type: application/json

{
    "username": "hecpabe",
    "name": "Héctor Paredes Benavides",
    "email": "hectorpbenavides@gmail.com",
    "password": "Abc123..",
    "description": "Esta es mi nueva descripción",
    "avatar": 1,
    "country": "España",
    "city": "Madrid",
    "preferences": ["hotel", "restaurant", "Ropa"],
    "allowAdvertising": false
}

###

DELETE http://localhost:3000/users/5 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sIjoidXNlciIsImlhdCI6MTY4MjQzNTk3OCwiZXhwIjoxNjgyNDQzMTc4fQ.n3uNrpEMKaAXU-yB8AaqAfiIYp4bkq_2J593GihFJ1M

###