POST http://localhost:3000/users/register HTTP/1.1
Content-Type: application/json

{
    "username": "@hecpabe",
    "name": "Héctor Paredes",
    "email": "hectorpbenavides@gmail.com",
    "password": "test123"
}

###

POST http://localhost:3000/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "hectorpbenavides@gmail.com",
    "password": "test123"
}

###

POST http://localhost:3000/users/restorepassword/email HTTP/1.1
Content-Type: application/json

{
    "email": "hectorpbenavides@gmail.com"
}

###

POST http://localhost:3000/users/restorepassword/code HTTP/1.1
Content-Type: application/json

{
    "email": "hectorpbenavides@gmail.com",
    "code": "123456"
}

###

PUT http://localhost:3000/users/restorepassword HTTP/1.1
Content-Type: application/json

{
    "email": "hectorpbenavides@gmail.com",
    "code": "123456",
    "password": "test123"
}

###

GET http://localhost:3000/users HTTP/1.1

###

GET http://localhost:3000/users/username HTTP/1.1

###

PUT http://localhost:3000/users/username HTTP/1.1
Content-Type: application/json

{
    "username": "hecpabe",
    "name": "Héctor Paredes Benavides",
    "email": "hectorpbenavides@gmail.com",
    "password": "1234",
    "new_password": "12345",
    "confirm_new_password": "12345",
    "country": "España",
    "city": "Madrid",
    "preferences": ["hotel", "restaurant"]
}

###

DELETE http://localhost:3000/users/username HTTP/1.1

###